apiVersion: v1
kind: Service
metadata:
  name: app-1-service-stable
spec:
  selector:
    app: app-1
    track: stable
  ports:
  - port: 8080
    protocol: TCP
    targetPort: express-port
  type: LoadBalancer
