apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deployment-unstable
  labels:
    app: app-1
    track: unstable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
      track: unstable
  template:
    metadata:
      labels:
        app: app-1
        track: unstable
    spec:
      containers:
      - name: app-1-container
        image: docker.io/npaduladvr/k8s-learning:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - name: express-port 
          containerPort: 3000
