apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: username
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: password
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: wp-secrets
                key: database
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - name: http-port 
          containerPort: 80
